[package]
name = "cdc"
version = "0.1.0"
license = "MIT"
readme = "README.md"
description = "A library for performing Content-Defined Chunking (CDC) on data streams."

authors = ["Vincent Cantin <vincent.cantin@le-moulin-studio.com>"]
homepage = "https://github.com/green-coder/cdc"
repository = "https://github.com/green-coder/cdc"

exclude = [
  "*.bin",
]
keywords = ["rabin", "cdc", "chunk", "merkle", "dedup"]

[dependencies]

[dev-dependencies]
arrayref = "0.3.7"
criterion = "0.5"
ring = "0.16.20"

[[bench]]
name = "benchmarks"
harness = false
